### ISSUE TITLE
link to plone integration points to drupal

### ISSUE THREAD

**Issue by pspeybro** [mathjax/MathJax-docs#110]
on this page: https://github.com/mathjax/MathJax-docs/blob/master/misc/platforms.rst

The link: MathJax integration for Plone 
points to http://drupal.org/project/mathjax

Where is the link for Plone?

**Comment by pspeybro** [comment]
in fact, it seems like these instructions work:
Installed it in Plone by simply going to Site Setup -> Site and add the source line from the MathJax website to the "JavaScript for web statistics support" section: 

<script type="text/javascript"
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>

**Comment by pkra** [comment]
Thanks for catching that! The link seems to have been lost during the website migration; I'm guessing it was https://github.com/collective/collective.mathjax but that seems quite dated so I've removed it for now.

> in fact, it seems like these instructions work:[...]

Thanks. We focus those links on plugins as the "edit theme/site/template" instructions quickly get out of hand; we have the general description below the list of links which hopefully covers this. If you have suggestions for improving that in general, please let us know (or simply make a pull request).

Thanks again.
