### ISSUE TITLE
`Queue()` accepts a list I think, no callback

### ISSUE THREAD

**Issue by kasperpeulen** [mathjax/MathJax-docs#125]
![image](https://cloud.githubusercontent.com/assets/1035299/10786569/31b31e64-7d6b-11e5-8d35-4aa558a98b9c.png)

Here it said that the `Queue` object accepts a callback, but I think it actually accepts a list right?

This is how I use it:
```javascript
MathJax.Hub.Queue(["Typeset",MathJax.Hub,"MathDiv"]);
```

**Comment by dpvc** [comment]
The list *is* a callback specification.  There are several ways to specify a callback.  See the [calback documentation](http://docs.mathjax.org/en/latest/api/callback.html#specifying-a-callback) for details.

**Comment by kasperpeulen** [comment]
Ah, I see now, thanks @dpvc

**Comment by kasperpeulen** [comment]
@dpvc Just to make sure I understand it correctly. 

Basically, `MathJax.Hub.Queue(["Typeset",MathJax.Hub,"MathDiv"])` is a shorter way of writing:

```javascript
MathJax.Hub.Queue(
  function() {
    MathJax.Hub.Typeset("MathDiv");
  }
);
```
