### ISSUE TITLE
tex2jax is missing in options/hub.html#configure-hub

### ISSUE THREAD

**Issue by kasperpeulen** [mathjax/MathJax-docs#126]
tex2jax is not described in http://docs.mathjax.org/en/latest/options/hub.html#configure-hub. I think this is one of the most used options. So it may be good to describe it there as well.

**Comment by dpvc** [comment]
The page you cite documents that configuration options for the `MathJax.Hub` component, so these are only the configuration options that are used directly by the `Hub`.  Other components, like the `text2jax` preprocessor, have their own configuration blocks, and their own documentation pages, such as the [tex2jax options](http://docs.mathjax.org/en/latest/options/tex2jax.html) page.  The hub page is not the list of most important options, it is the reference for all the options for the hub component.  It would not be appropriate to put the tex2jax options here.

A page that describes the most-used options could be part of the general documentation, I suppose but those are going to depend on the input and output selections, so there might have to be several such descriptions.  In any case, I don't think that belongs in the reference documentation, but rather in the general user documentation.

**Comment by pkra** [comment]
Also, tex2jax is the very next page in the documentation.

**Comment by kasperpeulen** [comment]
Just to make my context more clear. I'm writing a MathJax API for the dart language (which has a dart2js compiler). I want to write the API so that there is good code completion, and give warnings if the wrong options are passed:

![image](https://cloud.githubusercontent.com/assets/1035299/10843926/4dc632ac-7efc-11e5-8b1e-eaed625f2308.png)

I thought that this page was about all the options available to pass to `MathJax.Hub.Config()`. But I guess I misunderstood that. Is there a page for all the options for `MathJax.Hub.Config()` ?

**Comment by kasperpeulen** [comment]
oh nevermind, I got it

**Comment by pkra** [comment]
That sounds like a neat project though. Maybe we can get together for a chat some time.
