### ISSUE TITLE
add mathjax/papers

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-docs#129]
To https://github.com/mathjax/MathJax-docs/blob/v2.6-latest/misc/articles.rst, I think. But work in the rest.

**Comment by dpvc** [comment]
The two articles from 2010 no longer point to anything (404 page from www.mathjax.org).

You might also consider adding: ["MathJax: A Platform for Mathematics on the Web", *Notices of the American Mathematical Society*, **59** (2012) no. 2, 312–316.](http://www.ams.org/notices/201202/rtx120200312p.pdf)

**Comment by pkra** [comment]
> The two articles from 2010 no longer point to anything (404 page from www.mathjax.org).

Oops. fixed on the 2.6 branch.
