### ISSUE TITLE
wrapping large mathematical equations

### ISSUE THREAD

**Issue by 07961A1257** [mathjax/MathJax-docs#131]
Hi, We can wrap large mathematical equations even when browser is resized. When placed with automatic line breaks i'm able to break equations but whole page changes, I want certain portion of page to be changed. Can i do this? Please tell if it can be done...

<div class="MathToRender">
<math class="qml_qmath">
  <mrow>
    <mn>216</mn>
    <msup superscriptshift="1.3ex">
      <mrow>
        <mi>x</mi>
      </mrow>
      <mstyle scriptlevel="0" fontsize="0.75" displaystyle="true">
        <mrow>
          <mn>3</mn>
        </mrow>
      </mstyle>
    </msup>
    <mo> </mo>
    <mo>+</mo>
    <mo> </mo>
    <mn>216</mn>
    <msup superscriptshift="1.3ex">
      <mrow>
        <mi>x</mi>
      </mrow>
      <mstyle scriptlevel="0" fontsize="0.75" displaystyle="true">
        <mrow>
          <mn>2</mn>
        </mrow>
      </mstyle>
    </msup>
    <mi>y</mi>
    <mo> </mo>
    <mo>-</mo>
    <mo> </mo>
    <mn>432</mn>
    <msup superscriptshift="1.3ex">
      <mrow>
        <mi>x</mi>
      </mrow>
      <mstyle scriptlevel="0" fontsize="0.75" displaystyle="true">
        <mrow>
          <mn>2</mn>
        </mrow>
      </mstyle>
    </msup>
    <mi>z</mi>
    <mo> </mo>
    <mo>+</mo>
    <mo> </mo>
    <mn>72</mn>
    <mi>x</mi>
    <msup superscriptshift="1.3ex">
      <mrow>
        <mi>y</mi>
      </mrow>
      <mstyle scriptlevel="0" fontsize="0.75" displaystyle="true">
        <mrow>
          <mn>2</mn>
        </mrow>
      </mstyle>
    </msup>
    <mo> </mo>
    <mo>+</mo>
    <mo> </mo>
    <mn>288</mn>
    <mi>x</mi>
    <msup superscriptshift="1.3ex">
      <mrow>
        <mi>z</mi>
      </mrow>
      <mstyle scriptlevel="0" fontsize="0.75" displaystyle="true">
        <mrow>
          <mn>2</mn>
        </mrow>
      </mstyle>
    </msup>
    <mo> </mo>
    <mo>-</mo>
    <mo> </mo>
    <mn>288</mn>
    <mi>x</mi>
    <mi>y</mi>
    <mi>z</mi>
    <mo>
    </mo>
    <mo>+</mo>
    <mo> </mo>
    <mn>8</mn>
    <msup superscriptshift="1.3ex">
      <mrow>
        <mi>y</mi>
      </mrow>
      <mstyle scriptlevel="0" fontsize="0.75" displaystyle="true">
        <mrow>
          <mn>3</mn>
        </mrow>
      </mstyle>
    </msup>    
    <mo> </mo>
    <mo>-</mo>
    <mo> </mo>
    <mn>48</mn>
    <msup superscriptshift="1.3ex">
      <mrow>
        <mi>y</mi>
      </mrow>
      <mstyle scriptlevel="0" fontsize="0.75" displaystyle="true">
        <mrow>
          <mn>2</mn>
        </mrow>
      </mstyle>
    </msup>
    <mi>z</mi>
    <mo> </mo>
    <mo>+</mo>
    <mo> </mo>
    <mn>96</mn>
    <mi>y</mi>
    <msup superscriptshift="1.3ex">
      <mrow>
        <mi>z</mi>
      </mrow>
      <mstyle scriptlevel="0" fontsize="0.75" displaystyle="true">
        <mrow>
          <mn>2</mn>
        </mrow>
      </mstyle>
    </msup>
    <mo> </mo>
    <mo>-</mo>
    <mo> </mo>
    <mn>64</mn>
    <msup superscriptshift="1.3ex">
      <mrow>
        <mi>z</mi>
      </mrow>
      <mstyle scriptlevel="0" fontsize="0.75" displaystyle="true">
        <mrow>
          <mn>3</mn>
        </mrow>
      </mstyle>
    </msup>
  </mrow>
</math>
</div>

**Comment by pkra** [comment]
It's not clear what you're after. You might want to post to https://groups.google.com/forum/#!forum/mathjax-users for general purpose question; try to include a live sample (on codepen, jsbin etc) of what you're trying to do.

I also don't see the connection to the documentation repository.
