### ISSUE TITLE
options/ThirdParty.rst not very clear

### ISSUE THREAD

**Issue by ickc** [mathjax/MathJax-docs#145]
I was asking it in the MathJax repository but found it more appropriate to ask here:

from the `options/ThirdParty.rst`:

> Usually, third-party extensions have to be specified with their full paths (and matching loadComplete calls); this limits portability. To simplify this process, the MathJax configuration can include (possibly multiple) third-party locations for easier reference.

First, I found out a relative path is also fine, but isn't mentioned there. Secondly, I am confused by what it means by `(possibly multiple) third-party locations`. I was hoping it means it allows multiple fallback locations for the same extension. But probably it means different locations for different extensions.

Could you clarify the doc a bit on that paragraph? Thanks.

**Comment by dpvc** [comment]
> I am confused by what it means by "(possibly multiple) third-party locations".

This means that you can create as many prefixes like `[Contrib]` as you wish, one to each repository that you want to use.  E.g., `[Contrib]` could point to the third-party repository we maintain, while `[myFiles]` could point to your own server somewhere.  Then you could use

```
MathJax.Hub.Config({
   TeX: {extensions: ["[Contrib]/forminput/forminput.js", "[myFiles]/myExtension.js"]}
});
```

to load `forminput` from the main third-party repository, and `myExtension` from your own server.

> I was hoping it means it allows multiple fallback locations for the same extension.

No, this is not about fallback locations.  If MathJax fails to load an extension from the location it is requested, it does not try fallback locations.  The same is true of its own core files; if it can't load them from the location where MathJax.js itself was loaded, it doesn't try other locations.
