### ISSUE TITLE
Typo in "Getting started" page: the the

### ISSUE THREAD

**Issue by shreevatsa** [mathjax/MathJax-docs#147]
Very minor thing: at https://docs.mathjax.org/en/latest/start.html#downloading-and-installing-mathjax the second sentence currently reads: 

> To install MathJax on your own server, download the the latest distribution and unpack the archive and place the resulting MathJax folder onto your web server at a convenient location where you can include it into your web pages.

One of the "the"s should be removed.

**Comment by pkra** [comment]
Thanks.
