### ISSUE TITLE
Proguard rules for Mathjax?

### ISSUE THREAD

**Issue by gayathri-nair03** [mathjax/MathJax-docs#157]
MathJax does not render when I use proguard in my release app. What's the workaround for this?

**Comment by pkra** [comment]
I'm guessing you mean the Java tool in the context of Android app development. We haven't heard about any issues but we can't really help with Android development. If you can't provide more details on why MathJax fails, I'd suggest to ask on a more general forum about , e.g., stackoverflow.

**Comment by gayathri-nair03** [comment]
Hi @pkra : Thanks for the quick response. Anyway, I solved this issue. Had to add a few Proguard specific rules for the Android app:
# If your project uses WebView with JS, use the following
# and specify the fully qualified class name to the JavaScript interface
# class:
-keepclassmembers class fqcn.of.javascript.interface.for.webview {
  public *;
}
-keepclassmembers class * {
   @android.webkit.JavascriptInterface <methods>;
}

**Comment by pkra** [comment]
Glad to hear you could fix it. And thank you for sharing it here, too, @gayathri-nair03!
