### ISSUE TITLE
link to MathJax font help page is broken

### ISSUE THREAD

**Issue by xolotl** [mathjax/MathJax-docs#160]
The link to the MathJax font help page (http://www.mathjax.org/help/fonts) under "Firefox and local fonts" on the following doc page returns 404 and redirects to the MathJax home page:
https://github.com/mathjax/MathJax-docs/blob/master/installation.rst

**Comment by pkra** [comment]
Thanks for spotting that. From a quick look at the archives, the information that used to be at mathjax.org/help/fonts was largely incorporated into the docs (except for general information on how to install fonts on an OS is missing which is now outdated and probably out of scope for our docs). 

We'll remove the link.
