### ISSUE TITLE
link to v2.7-latest.zip doesn't work

### ISSUE THREAD

**Issue by noniwoo** [mathjax/MathJax-docs#174]
Link at page http://docs.mathjax.org/en/latest/installation.html going to https://github.com/mathjax/MathJax/archive/v2.7-latest.zip does not work.

**Comment by pkra** [comment]
Thanks for catching that. 

Fixed in https://github.com/mathjax/MathJax-docs/commit/5fea96c9e9b6d71f00a1ec51175ee967e22a118e
