### ISSUE TITLE
Missing example in http://docs.mathjax.org/en/latest/options/a11y-extensions.html#a11y-extensions

### ISSUE THREAD

**Issue by cebola2** [mathjax/MathJax-docs#175]
I believe an intended example is missing after "e.g." on http://docs.mathjax.org/en/latest/options/a11y-extensions.html#a11y-extensions

The accessibility menu extension can then be controlled in the configuration block for the MathJax menu, e.g.,

Note

The accessibility menu is part of all combined configurations.

**Comment by pkra** [comment]
Thanks. It's in the source but something must be off to cause sphinx from rendering it.

**Comment by pkra** [comment]
Fixed. The site should regenerate in a few minutes.
