### ISSUE TITLE
update accessibility-features

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-docs#222]
Would you be open to me re-writing this so that the a11y extensions are prominently mentioned as the real solution and the AssistiveMML is more strongly discouraged as a solution (e.g., likely to be deprecated in v3)? 

I've had one too many conversations where people skip over the a11y extension part and just read the details for AssistiveMML.js.

**Comment by dpvc** [comment]
That would be great, thanks.  I look forward to your pull request.

**Comment by pkra** [comment]
PR was never merged.
