### ISSUE TITLE
"Making a Custom Build of MathJax" is missing information on node modules

### ISSUE THREAD

**Issue by christianp** [mathjax/MathJax-docs#235]
I'm trying to follow [the instructions on building a custom extension in MathJax v3](http://docs.mathjax.org/en/latest/web/webpack.html#a-custom-extension). 

I installed mathjax-full with `npm install mathjax-full`, and wrote all the files described in the instructions. When I ran `makeAll`, it hung for a couple of minutes before timing out. I then ran `npx webpack --display-modules` which let me see stderr. It was complaining that webpack-cli wasn't installed.

None of the devDependencies of mathjax-full are installed. I finally got around it by setting up my own `package.json` and copying all the devDependencies from mathjax-full:

```
{
  "name": "clpext",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {},
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-preset-env": "^1.6.1",
    "copyfiles": "^2.1.1",
    "diff": "^3.5.0",
    "lodash": "^4.17.14",
    "rimraf": "^3.0.0",
    "tape": "^4.8.0",
    "tslint": "^3.15.0",
    "tslint-jsdoc-rules": "*",
    "tslint-unix-formatter": "*",
    "typescript": "^3.5.2",
    "typescript-tools": "^0.3.1",
    "uglifyjs-webpack-plugin": "^2.1.2",
    "webpack": "4.19.0",
    "webpack-cli": "^3.2.3",
    "mathjax-full": "^3.0.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Christian Lawson-Perfect <christianperfect@gmail.com>",
  "license": "Apache-2.0"
}
```

Is this a step that's missing from the instructions, or should npm have installed all those packages alongside mathjax-full? 

I just don't get npm, and my blood pressure doubles when I use it, so I've avoided it as much as I can, which has led to me avoiding MathJax v3 throughout its development process.

**Comment by dpvc** [comment]
You are right, m the dev dependencies don't get installed automatically.  I didn't notice that since I have them installed already (oops).  The documentation does need to be updated to include the needed installs.  Not all the mathjax-full dev dependencies are needed to make the component.  I think just the webpack ones would be enough.  I'll work out the needed list and modify the documentation.

**Comment by dpvc** [comment]
I've updated the documentation.  Thanks!
