### ISSUE TITLE
Typo in Startup Option page

### ISSUE THREAD

**Issue by lesomnus** [mathjax/MathJax-docs#247]
Typo in [here](https://github.com/mathjax/MathJax-docs/blob/ea477998a92a1900c34fd3849b506df7fe79d64b/options/startup/startup.rst)
```js
MathJax = {
    loader: {
        ...
    }
}
```
must be
```js
MathJax = {
    startup: {
        ...
    }
}
```

I had a tough day

**Comment by dpvc** [comment]
Thanks!  I'll make the change when I update the site (there are several items to be fixed, so it should be soon).

**Comment by dpvc** [comment]
This is now fixed.
