### ISSUE TITLE
Access tex input after typesetting the doc

### ISSUE THREAD

**Issue by HariDongli** [mathjax/MathJax-docs#249]
Hi, 
I'm looking to access the tex through code after typesetting the doc,

![Screen Shot 2020-02-21 at 11 24 11 PM](https://user-images.githubusercontent.com/13314512/75058623-5a81b680-5501-11ea-9b9c-3a3abd7f37a1.png)

In the browser, i'm able to see & copy the tex by following menu popup,
https://github.com/mathjax/MathJax-src/blob/1d5ce9837c82f1d12efec8da829c2138bd640c08/ts/ui/menu/Menu.ts#L303

the above function returns the original tex, when clicked on show as tex commands

MathJax version: 3

Looking for the docs/help to resolve my issue

Thanks

**Comment by dpvc** [comment]
See [my answer](https://groups.google.com/d/msg/mathjax-users/x5Z7JBElOas/Z4DYXY_nEQAJ) in the MathJax User Forum for some suggestions on how to accomplish your goal.

Note that this tracker is for bugs in the MathJax documentation, not general questions about MathJax, which are better asked in the forum linked above.
