### ISSUE TITLE
Broken reference to list of macros from the FAQ page

### ISSUE THREAD

**Issue by dainiak** [mathjax/MathJax-docs#256]
https://docs.mathjax.org/en/latest/misc/faq.html

![image](https://user-images.githubusercontent.com/2994860/79571086-443c4500-80c3-11ea-8f3d-eebec8c42c5a.png)

**Comment by dpvc** [comment]
Thanks for the report.  There were a number of other broken links on that page as well (due to the mechanism by which they were being linked).  I searched the docs for additional occurrences of that incorrect link pattern, and I think I caught them all.
