### ISSUE TITLE
Bad links in docs.mathjax.org

### ISSUE THREAD

**Issue by NSoiffer** [mathjax/MathJax-docs#257]
In looking at [Articles and Presentations](http://docs.mathjax.org/en/latest/misc/articles.html), none of the links that point to github work. E.g, the first link
> Towards Universal Rendering in MathJax (W4A 2016) by Davide Cervone, Peter Krautzberger, Volker Sorge, MathJax, 2016

points to https://github.com/mathjax/papers/blob/newpapers/W4A/w4a16-accessible.pdf, but that results in a 404 (not found).

**Comment by dpvc** [comment]
Thanks, I've fixed the links.
