### ISSUE TITLE
MathJax.typesetPromise()

### ISSUE THREAD

**Issue by mhchem** [mathjax/MathJax-docs#263]
In section http://docs.mathjax.org/en/latest/web/typeset.html#handling-asynchronous-typesetting,
shouln't

    promise = promise.then(() => {code(); return MathJax.typesetPromise()})

rather read

    promise = promise.then(() => {return MathJax.typesetPromise(code())})

to ensure that only certain DOM parts are re-rendered?

**Comment by dpvc** [comment]
Yes, you are correct.  That should be corrected.
