### ISSUE TITLE
Dead link in math editors wiki page

### ISSUE THREAD

**Issue by tannerlegvold** [mathjax/MathJax-docs#278]
The third link in the Open Source section of [this wiki page](https://github.com/mathjax/MathJax-docs/wiki/List-of-web-based-math-editors) is dead, so it should probably removed. 

Some additional investigating: the Wayback Machine hadn't archived it. But it had archived this [http://sethi.host22.com/Live-Mathjax-Editor](https://web.archive.org/web/20200405084245/http://sethi.host22.com:80/Live-Mathjax-Editor) (this URL is also no longer available, this is a Wayback link). Doesn't look like the Wayback Machine stored the info well enough to reproduce whatever effect was working originally though.

**Comment by dpvc** [comment]
Thanks for the report.  Those pages are no longer maintained, and are just for historical interest.
