### ISSUE TITLE
MathJax CDN doesn't have some environments such as empheq

### ISSUE THREAD

**Issue by ickc** [mathjax/MathJax-docs#290]
When setting up to use the extension empheq, the following error occur:

    https://cdn.jsdelivr.net/npm/mathjax@3/es5/input/tex/extensions/empheq.js net::ERR_ABORTED 404

In https://www.jsdelivr.com/package/npm/mathjax?path=es5%2Finput%2Ftex%2Fextensions, empheq aren't listed there.

I file the issue here since the doc recommend using jsdelivr. Where is the most suitable place to file this issue?

Thanks.

Edit: more info:

- empheq is [here](https://github.com/mathjax/MathJax-src/tree/master/ts/input/tex/empheq) at source.

- The [3.2 release note](https://github.com/mathjax/MathJax-src/releases/tag/3.2.0) here mentions empheq is added and is available in `-full` component.

- The [doc mention a method to load empheq here](https://docs.mathjax.org/en/latest/input/tex/extensions/empheq.html).

- However, [empheq is not in the mathjax/MathJax repo](https://github.com/mathjax/MathJax/tree/master/es5/input/tex/extensions) (probably where the CDNs are getting the files from?)

In the end, either the load method mentioned in the doc, or the `-full` configuration includes the empheq.

**Comment by dpvc** [comment]
See mathjax/MathJax#2762 for a workaround.  Thanks for reporting the issue.

**Comment by pkra** [comment]
I believe this can be closed as fixed (in 3.2.1)

**Comment by dpvc** [comment]
It can be closed when 3.2.1 is released, which it isn't yet.  But yet, it can be then.
