### ISSUE TITLE
input/tex/macros - link packages to their docs page

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-docs#298]
It would be nice if the second column was linking to the relevant packages.

**Comment by pkra** [comment]
If I can remember enough sphinx syntax, I'll take a stab at it.

**Comment by dpvc** [comment]
The tables are now generated by code that Volker has written, so any changes would need to be made in that code.  I don't remember if it is in a public repository or not.  @zorkow, is it available?

**Comment by pkra** [comment]
> The tables are now generated by code that Volker has written, so any changes would need to be made in that code. I don't remember if it is in a public repository or not. @zorkow, is it available?

Ah, thanks. I'll hold off then.

**Comment by pkra** [comment]
This seems dead enough to close.
