### ISSUE TITLE
Document resetEquationNumbers

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax-docs#3]
The TeX input jax's `resetEquationNumbers` method needs to be added to the documentation.

**Comment by Klortho** [comment]
> This was fixed.

Link?  Google [finds nothing](https://www.google.com/search?q=site%3Amathjax.readthedocs.org+resetEquationNumbers)

**Comment by pkra** [comment]
I think this was erroneously closed. From the linked PR (#59), it sounds like I worked on a branch accidentally named issue3 instead of issue54. I'm guessing I later went through issues, saw the PR link and closed this without checking.

I actually don't know what @dpvc wanted documented here. What are you looking for @Klortho?

**Comment by Klortho** [comment]
[This](https://groups.google.com/d/msg/mathjax-users/cpwy5eCH1ZQ/8lKM4Ls3z4MJ). I just ran into this problem, in our [render-math](https://github.com/ncbi/render-math) service.

**Comment by pkra** [comment]
> This. 

Ah, thanks.

> in our render-math service.

Nice. Are you aware of MathJax-node?

**Comment by Klortho** [comment]
I was aware of it, yes. You guys got that started after we had already forked svgbin and did quite a bit of work on it.  Not sure if/when it'll be worth going back and replacing what we have now.

**Comment by pkra** [comment]
Ah ok, that makes sense. There are multiple service built on mathjax-node now (mathjax-server, mathoid, mmlcloud); it would be good to bring people together to share experiences and identify improvements. Maybe we can chat some time? I'll ping you by email.

**Comment by pkra** [comment]
@dpvc I guess documentation should go into http://docs.mathjax.org/en/v2.6-latest/tex.html#automatic-equation-numbering ? I can't see how to fit it into http://docs.mathjax.org/en/v2.6-latest/options/TeX.html very well (but perhaps it does?).

**Comment by dpvc** [comment]
It may be better in the [dynamic HTML](http://docs.mathjax.org/en/v2.6-latest/advanced/typeset.html) section rather than the TeX section, since that is when it would need to be used.

**Comment by pkra** [comment]
A fix is in the 2.6-latest branch. I also added a link to http://docs.mathjax.org/en/v2.6-latest/tex.html#automatic-equation-numbering.
