### ISSUE TITLE
remove polyfill.io references

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-docs#334]
The domain is apparently being acquired and users are already experiencing problems https://fosstodon.org/@haubles/111995201660738714

**Comment by dpvc** [comment]
Thanks, Peter.  I will definitely change that, and make an announcement on the forum lists.

**Comment by pkra** [comment]
Some more background in https://github.com/josdejong/mathjs/pull/3167

**Comment by mhils** [comment]
This should probably be expedited in light of https://sansec.io/research/polyfill-supply-chain-attack. https://www.mathjax.org/#gettingstarted still references polyfill.io.

**Comment by dpvc** [comment]
I have updated the web site to remove `polyfill.io`, to give a warning about its use, and to link to the article cited.
