### ISSUE TITLE
collection of readthedocs theme issues

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-docs#45]
Moving these from https://github.com/mathjax/MathJax-docs/issues/32#issuecomment-42549476 to their own issue to track.
- [x] left-hand sidebar, all the links from the home page appear, but not separated into their categories.
- [x] the alphabetical list of LaTeX commands doesn't format well (in Safari) due to the bold monospaced font. 

These have been reported upstream at https://github.com/snide/sphinx_rtd_theme/issues/120 and https://github.com/snide/sphinx_rtd_theme/issues/121 and 

Other solutions: override the CSS, https://github.com/snide/sphinx_rtd_theme/issues/117

**Comment by dpvc** [comment]
I think the theme now handles this.  It seems correct to me, so I'm closing this.
